### ISSUE TITLE
大佬这个咋用

### ISSUE THREAD

**Issue by fuhua666** [lujunji-xiaolu/mooc-helper#1]
大佬！有打包好的吗?我不会用哎

**Comment by ghost** [comment]
This is an online site
https://mooc-helper.web.cloudendpoint.cn/

**Comment by fuhua666** [comment]
哥，我测试了一下，他好像获取不了spoc的课程，添加不了也获取不了答案

**Comment by ghost** [comment]
好的，我会在1~2天内尝试解决该问题。

**Comment by fuhua666** [comment]
![mmexport1648784442596](https://user-images.githubusercontent.com/78785680/161363750-a05c1c3c-b602-4406-a494-0aa08bad576f.jpg)
我抓取了token，为啥填入没用啊?

**Comment by ghost** [comment]
You are so lucky. 这个请求的 mob-token 位于请求头中，虽然它的字段为“mob-token”，但它不是我们想要的 mob-token。试试其它请求，寻找在 params/body 中存在 mob-token 字段的 GET/POST 请求

**Comment by fuhua666** [comment]
不能在网站直接输入账号密码吗?，然后直接获取课程吗？这样感觉更简单更方便

**Comment by ghost** [comment]
😢我之前尝试过，但是对于我来说“破解”慕课的登录接口太困难了

**Comment by fuhua666** [comment]
要不您帮我抓取一下，对我来说抓取mob-token也困难

**Comment by ghost** [comment]
你已经快成功了，试试这个 https://github.com/lujunji-xiaolu/mooc-helper#setMobToken

**Comment by fuhua666** [comment]
![Screenshot_2022-04-03-10-23-27-620_com guoshi httpcanary premium](https://user-images.githubusercontent.com/78785680/161410425-55bd679f-f449-4aed-bd68-46de8fdb88eb.jpg)
按照您的方法，我没成功

**Comment by ghost** [comment]
需要先确保开启抓包，然后打开 中国大学MOOC 应用，导航至 学习 ，等待该页面加载完成。

**Comment by fuhua666** [comment]
抓包软件是否要root?

**Comment by ghost** [comment]
我不太确定。不过我没有添加HttpCanary根证书至系统。

**Comment by fuhua666** [comment]
![Uploading IMG_20220403_140634.jpg…]()
那您帮我看看是这三个是吗

**Comment by fuhua666** [comment]
![1db3894223f881a2](https://user-images.githubusercontent.com/78785680/161414300-f872e26f-4640-4139-946d-a50dfbff8acf.jpg)
您帮我看看这三个是哪个

**Comment by ghost** [comment]
任意一个均可

**Comment by fuhua666** [comment]
![6b66ca9af573b438](https://user-images.githubusercontent.com/78785680/161415701-1c36507c-bf45-4025-a30b-3f8bb1939a9c.jpg)
我点开就是这个，和之前一样的

**Comment by lujunji-xiaolu** [comment]
你是不是中国大学MOOC慕课上没有添加课程呀？

**Comment by fuhua666** [comment]
谢谢您的耐心解答，我已经成功了。摸索了半天。冒昧问一句考试查答案会不会支持😁

**Comment by ghost** [comment]
会，如果能够实现的话
