### ISSUE TITLE
查询期末考试答案会导致直接用完一次考试机会，直接提交了，甚至不知道多少分。

### ISSUE THREAD

**Issue by TakotsuboChen** [lujunji-xiaolu/mooc-helper#13]

**Comment by ghost** [comment]
这是因为考试有**时间限制**，README.md中提及过这个问题。
### 原因
- 查询操作与开始考试(开始测试)都会产生一次记录。正常情况下这并没有什么问题，但是如果有**时间限制**，一旦到达时间截至点，这次记录会被慕课后台直接提交，并进行计分。也就是说，没有时间限制的情况下，查询操作所产生的记录是不会提交的；反之，有时间限制的情况下，到达时间截至点，查询操作所产生的记录会被提交。
- 查询操作所产生的记录是空白记录，是没有用户的答题情况的。简单的说，一张白卷。
### 如何避免
查询后，抓紧时间查看答案(时间截至前)，然后提交。也就说要赶在查询操作所产生的记录被后台提交之前。

**Comment by ghost** [comment]
建议你向老师说你不小心触碰到提交按钮，题还没做完就提交了。如果老师人好的话，老师那边可以给你设置一次重新考试的机会。

**Comment by TakotsuboChen** [comment]
好的，谢谢
