### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Scarbal486** [lujunji-xiaolu/mooc-helper#17]
请问能不能教一下怎么用苹果手机或者PC端抓mob-taken？谢谢QAQ

**Comment by Scarbal486** [comment]
我用的模拟器好像装不了根证书（不知道有没有影响），然后搜索List的时候总是显示无结果

**Comment by xiaolu-lujunji** [comment]
希望这篇文章能解决你的问题：https://blog.csdn.net/qq_24857309/article/details/118600865

**Comment by Scarbal486** [comment]
我把抓包详情-请求-请求主体那里的mob-taken粘贴进去了，但是没有反应，请问怎么处理

**Comment by Scarbal486** [comment]
哦哦我明白了，IOS那里的mob-taken最后多了一串东西，删了之后就可以搜到了，谢谢大大
