### ISSUE TITLE
课程问题

### ISSUE THREAD

**Issue by jianabc** [lujunji-xiaolu/mooc-helper#2]
您好，我的课程uid=1467502475这个课程无法添加，测验作业也查询不了。

**Comment by ghost** [comment]
你可以将这个慕课课程的网址评论出来吗？我想确定一下个id是否正确。

**Comment by jianabc** [comment]
https://www.icourse163.org/spoc/learn/HBSX-1464538221?tid=1467502475#/learn/announce

**Comment by ghost** [comment]
非常抱歉，目前SPOC学校专有课程无法添加，因为添加课程接口使用的mob-token目前是我本人的，而我目前没有得到对应学校的学生认证。

**Comment by ghost** [comment]
我这几天会尝试实现登录功能。如果能够实现，我会在第一时间回复你。

**Comment by jianabc** [comment]
好的谢谢，麻烦您了。
