### ISSUE TITLE
请求出错, 请检查后重试

### ISSUE THREAD

**Issue by C315703603** [lujunji-xiaolu/mooc-helper#20]
![)KNZM$QVLB` D BGW1P1KZ6](https://user-images.githubusercontent.com/103497700/198861436-5bbe6270-5cbf-4773-91d3-9b8207cf0df7.png)
其他课程正常，就这个课程出不来

**Comment by xiaolu-lujunji** [comment]
这个课程是否已经关闭了呢？

**Comment by C315703603** [comment]
没有关闭，开课截止12月18号，而且目前课程已更新12周，没有开期末考试。但是通过MOB-TOKEN获取的该课程中最高就是10周无12周而且已显示期末考试。而且无法获取答案

**Comment by C315703603** [comment]
![P 3I)F6087{K~I94Y3 )U3N](https://user-images.githubusercontent.com/103497700/203486874-0691caf2-3d49-4f72-9487-2bfb1a0ca383.png)
这个是课程目前更新的。
![J 6J)E6NU5Q){0LL3VE``LQ](https://user-images.githubusercontent.com/103497700/203486957-3f898d35-6eea-489e-a7fa-42846603c677.png)
这是目前通过MOB-TOKEN获取的课程。

**Comment by xiaolu-lujunji** [comment]
问题已修复，你试试。（若使用桌面应用，请确保其为最新版本）

**Comment by C315703603** [comment]
可以了大佬，万分谢谢。
