### ISSUE TITLE
请求出错登录信息过期

### ISSUE THREAD

**Issue by jianabc** [lujunji-xiaolu/mooc-helper#21]
为啥显示登录信息过期啊，mob-token我抓了几次了

**Comment by xiaolu-lujunji** [comment]
你可以描述一下你的获取 mob-token 的操作步骤吗？

**Comment by jianabc** [comment]
就是按照视频一步一步操作的，我之前也抓取过，也成功了，但是好久没用现在又不行了

**Comment by xiaolu-lujunji** [comment]
目前问题可以定位在 mob-token 上，是 mob-token 没有正确获取到。你可以在检查一下获取的关键步骤。
1. mob-token 是 getAllMyCourseList/v2 中的请求参数。
2. 确保复制粘贴 mob-token 时无误。
