### ISSUE TITLE
系统检测您的帐号已经于00:00在其他设备上登录，如非本人操作，建议检查帐号安全

### ISSUE THREAD

**Issue by Whiskium** [lujunji-xiaolu/mooc-helper#22]
我的手机 A 无法安装 HttpCanary 证书，便使用淘汰的手机 B 安装了 HttpCanary 并成功抓包，经在桌面端测试可以正常使用，于是换回手机 A 登录，此后始终提示如标题，无法正常获取了，桌面端和网站都是，使用手机 B 重新登录后依然如此。不知该如何解决？

**Comment by xiaolu-lujunji** [comment]
试一试退出手机 B 的登录

**Comment by Whiskium** [comment]
> 试一试退出手机 B 的登录

经测试，无论是仅退出、退出重新登录、卸载重新登录都不行。

**Comment by xiaolu-lujunji** [comment]
目前能够确定，在使用时保持手机 A 的慕课 App 保持登出状态就不会出现上述提示。至于原因，解释起来有点复杂。

**Comment by Whiskium** [comment]
依然不行…不太清楚内在原理，不知道桌面端/网站的解析是否依赖于后端，会不会是服务器缓存之类的原因，不知道本地部署能不能解决。

**Comment by xiaolu-lujunji** [comment]
好吧。不过至少能够确定使用哪台手机登录的 token ，请求时慕课后台就知道用户来自哪台手机。

**Comment by Whiskium** [comment]
那有什么解决方法吗？如果暂时没有的话我先试试本地部署吧，不过我不懂 TypeScript，不知可否简单教一下😁

**Comment by xiaolu-lujunji** [comment]
其实本地部署也没有用😊。因为这个项目最核心的逻辑就是给慕课后台发请求，获取答案的接口就是来自慕课手机端的接口。只不过慕课做了 CSRF 防范措施，请求时需要携带 csrfToken (mob-token)。
目前我也不知道问题出在哪里。我目前的想法就是要保证单一手机端登录，且 token 得来自那个单一手机端。

**Comment by Whiskium** [comment]
好吧，那我再找找有没有什么解决方法…还是谢谢了。
