### ISSUE TITLE
关于mob-token的疑问

### ISSUE THREAD

**Issue by cro3odile** [lujunji-xiaolu/mooc-helper#23]
mob-token是手机app特有的吗 
试图在手机浏览器 电脑网页 上抓包 都没有抓到

**Comment by xiaolu-lujunji** [comment]
移动端和 PC 端使用的后台接口不同，移动端采取 mob-token 存储会话信息。所以只有移动端的 (某些) 请求才会携带 mob-token。

**Comment by cro3odile** [comment]
> 移动端和 PC 端使用的后台接口不同，移动端采取 mob-token 存储会话信息。所以只有移动端的 (某些) 请求才会携带 mob-token。

受教了
