### ISSUE TITLE
能不能强调一下设置mob-token的后果555

### ISSUE THREAD

**Issue by ginnnnnncc** [lujunji-xiaolu/mooc-helper#3]
突然想到拿慕课测验答案的方法，赶紧去看了下自己慕课的测验，全是0分555555

**Comment by ghost** [comment]
因为查询操作相当于开启一次测验。如果这次测试是定时的，到时间点后慕课后台会自动提交。
我也遇到了相同的情况，在那之后我便查询完后立即提交一次，保证一次有效成绩。
