### ISSUE TITLE
无法安装CA证书，请问如何解决

### ISSUE THREAD

**Issue by Norlan-Ch** [lujunji-xiaolu/mooc-helper#31]
作者你好，我的系统是Xiaomi HyperOS 1.0.2.0.ULFCNXM，跟着视频有如下问题：
1.无法像视频中显示的自动安装CA证书，点击安装后有应用内弹窗（图1），点击‘关闭’后也并未安装。
2.进入到系统CA证书安装界面无法找到应用，也就无法安装（图2）。
3.解压apk后找到疑似CA证书文件‘c.crt’，重复2操作选择该文件显示需要私钥安装。

![1](https://github.com/lujunji4113/mooc-helper/assets/92942825/d29fca35-549b-4b62-b2e1-028a8c2c94f7)
[
![2](https://github.com/lujunji4113/mooc-helper/assets/92942825/f52a9320-7450-4706-9c40-9cda07f98085)
](url)
![3](https://github.com/lujunji4113/mooc-helper/assets/92942825/7b6b5e8c-3e78-4f86-b037-f76ac7ed8ee9)

**Comment by whale4113** [comment]
已更新 README.md，试一试 [PCAPdroid](https://github.com/lujunji4113/mooc-helper/blob/develop/docs/pcapdroid.md) 应用，看能不能解决问题。

**Comment by Norlan-Ch** [comment]
可以了，谢谢你！
