### ISSUE TITLE
中国大学MOOC  SPOC课程无法获取MOB-TOKEN

### ISSUE THREAD

**Issue by hujihan** [lujunji-xiaolu/mooc-helper#32]
![image](https://github.com/lujunji4113/mooc-helper/assets/46958243/3007cc26-d8fa-484e-8851-e8270bc01acc)
![1c51a3569905bd8d2db59e8aa15f549](https://github.com/lujunji4113/mooc-helper/assets/46958243/2d07fef1-1a4f-453b-bc51-db5621112b0b)

**Comment by whale4113** [comment]
可以多尝试看看其它路径的 HTTP 请求，截图中的 HTTP 请求应是登陆请求，mob-token 在 HTTP 响应体中。

![Screenshot_20240605_191534.jpg](https://github.com/lujunji4113/mooc-helper/assets/124325415/e2bdae8a-312c-4afd-bf6f-85720aca6c0f)
