### ISSUE TITLE
IOS用户抓包mob-token输入后显示登录失败或您的登录信息已过期

### ISSUE THREAD

**Issue by awapwq233** [lujunji-xiaolu/mooc-helper#34]
抓包地址和安卓不一样，在 `https://ke-api.study.163.com/my/course.json` 下找到了mob-token，反复刷新多次mob-token不变，一直登录失败，求问解决方案

![image](https://github.com/user-attachments/assets/58941c49-1ccb-4418-93fd-d8352c137706)

![image](https://github.com/user-attachments/assets/2b5b790f-4ca6-439b-b7a5-e074327fd157)

**Comment by whale4113** [comment]
可以提供一下你使用的 App 的版本吗？

**Comment by awapwq233** [comment]
您好，我已经成功了，在另外的位置也有mob-token，上面这个是假的，感谢您！

**Comment by StationSu** [comment]
您好，我有相同的问题，请问您说的“另外的位置”具体是指哪里？

**Comment by whale4113** [comment]
@StationSu 试一试查看域名为 www.icourse163.org 的请求

**Comment by StationSu** [comment]
感谢回复
目前的情况是iPad mini6，iPad OS 18.1.1，中国大学慕课版本4.30.3，抓包过程中未发现来自“http://www.icourse163.org/”的请求，图片链接如下
https://github.com/user-attachments/assets/b9ba2d3f-9cc8-4e81-ac28-d6ebcff21389

**Comment by StationSu** [comment]
> @StationSu 试一试查看域名为 [www.icourse163.org](http://www.icourse163.org) 的请求

找到了，非常感谢
