### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by Yeemkt** [lujunji-xiaolu/mooc-helper#4]
他说的mob -token的，有啥后果啊

**Comment by ghost** [comment]
当查询了有时间限制的单元测验后，对应的单元测验会有一次0分的提交。

![image](https://user-images.githubusercontent.com/95520590/163171308-01942218-a727-4e0a-97cc-1e1c14fb3763.png)

产生这个情况需要满足以下条件：
1、设置 mob-token。
2、单元测验有时间限制。
