### ISSUE TITLE
作者大大，今天好像用不了

### ISSUE THREAD

**Issue by TakotsuboChen** [lujunji-xiaolu/mooc-helper#6]
无法通过TID添加课程了

**Comment by ghost** [comment]
可以把该门课程的 tid 评论出来吗？我看看问题具体出在哪里。

**Comment by TakotsuboChen** [comment]
这个：1467061502，合肥工业大学高等数学（下）

**Comment by TakotsuboChen** [comment]
> 可以把该门课程的 tid 评论出来吗？我看看问题具体出在哪里。

这个：1467061502，合肥工业大学高等数学（下）

**Comment by ghost** [comment]
问题暂时解决了

**Comment by ghost** [comment]
请查看新网站：https://mooc-helper.vercel.app/
