### ISSUE TITLE
云函数接口作者考虑开源吗

### ISSUE THREAD

**Issue by bamboo3333** [lujunji-xiaolu/mooc-helper#7]

**Comment by ghost** [comment]
哈哈😁。其实云函数接口只是慕课接口的代理，因为在浏览器端直接访问慕课接口会跨域。
目前网站正在迁移至vercel，慕课接口的具体信息也会在源码中逐步体现出来。
```js
// 获取已添加的课程信息
const res = await axios({
    method: 'POST',
    url: 'https://www.icourse163.org/mob/course/getAllMyCourseList/v2',
    params: {
        p: "xxx",
        psize: "xxx",
        'mob-token': "xxx",
        type: 30
    }
})
// 获取课程章节信息
const res = await axios({
    method: 'POST',
    url: 'https://www.icourse163.org/mob/course/courseLearn/v1',
    params: {
        'mob-token': "xxx",
        cid: "xxx",
        tid: "xxx"
    }
})
// 获取单元作业信息
const res = await axios({
    method: 'POST',
    url: 'https://www.icourse163.org/mob/course/homeworkPaperDto/v1',
    params: {
        aud: “xxx”,
        'mob-token': "xxx",
        tid: "xxx"
    }
})
// 获取单元测验信息
const res = await axios({
  method: 'POST',
  url: 'https://www.icourse163.org/mob/course/paperDetail/v1',
  params: {
    'mob-token': "xxx",
    testId: "xxx",
    isExercise: true,
    withStdAnswerAndAnalyse: true
  }
});
```
使用的核心接口如上，这些接口信息是通过手机抓包获取的。

**Comment by chenshiforever** [comment]
> 哈哈grin。其实云函数接口只是慕课接口的代理，因为在浏览器端直接访问慕课接口会跨域。 目前网站正在迁移至vercel，慕课接口的具体信息也会在源码中逐步体现出来。
> 
> ```js
> // 获取已添加的课程信息
> const res = await axios({
>     method: 'POST',
>     url: 'https://www.icourse163.org/mob/course/getAllMyCourseList/v2',
>     params: {
>         p: "xxx",
>         psize: "xxx",
>         'mob-token': "xxx",
>         type: 30
>     }
> })
> // 获取课程章节信息
> const res = await axios({
>     method: 'POST',
>     url: 'https://www.icourse163.org/mob/course/courseLearn/v1',
>     params: {
>         'mob-token': "xxx",
>         cid: "xxx",
>         tid: "xxx"
>     }
> })
> // 获取单元作业信息
> const res = await axios({
>     method: 'POST',
>     url: 'https://www.icourse163.org/mob/course/homeworkPaperDto/v1',
>     params: {
>         aud: “xxx”,
>         'mob-token': "xxx",
>         tid: "xxx"
>     }
> })
> // 获取单元测验信息
> const res = await axios({
>   method: 'POST',
>   url: 'https://www.icourse163.org/mob/course/paperDetail/v1',
>   params: {
>     'mob-token': "xxx",
>     testId: "xxx",
>     isExercise: true,
>     withStdAnswerAndAnalyse: true
>   }
> });
> ```
> 
> 使用的核心接口如上，这些接口信息是通过手机抓包获取的。

这个东西，不建议直接放出来。。

**Comment by bamboo3333** [comment]
> 哈哈😁。其实云函数接口只是慕课接口的代理，因为在浏览器端直接访问慕课接口会跨域。 目前网站正在迁移至vercel，慕课接口的具体信息也会在源码中逐步体现出来。
> 
> ```js
> // 获取已添加的课程信息
> const res = await axios({
>     method: 'POST',
>     url: 'https://www.icourse163.org/mob/course/getAllMyCourseList/v2',
>     params: {
>         p: "xxx",
>         psize: "xxx",
>         'mob-token': "xxx",
>         type: 30
>     }
> })
> // 获取课程章节信息
> const res = await axios({
>     method: 'POST',
>     url: 'https://www.icourse163.org/mob/course/courseLearn/v1',
>     params: {
>         'mob-token': "xxx",
>         cid: "xxx",
>         tid: "xxx"
>     }
> })
> // 获取单元作业信息
> const res = await axios({
>     method: 'POST',
>     url: 'https://www.icourse163.org/mob/course/homeworkPaperDto/v1',
>     params: {
>         aud: “xxx”,
>         'mob-token': "xxx",
>         tid: "xxx"
>     }
> })
> // 获取单元测验信息
> const res = await axios({
>   method: 'POST',
>   url: 'https://www.icourse163.org/mob/course/paperDetail/v1',
>   params: {
>     'mob-token': "xxx",
>     testId: "xxx",
>     isExercise: true,
>     withStdAnswerAndAnalyse: true
>   }
> });
> ```
> 
> 使用的核心接口如上，这些接口信息是通过手机抓包获取的。

感谢，了解了
