### ISSUE TITLE
作者大大，我有个问题

### ISSUE THREAD

**Issue by penperlpa** [lujunji-xiaolu/mooc-helper#9]
那个马上就要停止服务的旧版是已经不能用了吗，我查看以前已经添加过的课程也看不了了😥😫

**Comment by ghost** [comment]
是的

**Comment by penperlpa** [comment]
那新版该怎么使用呢，我现在知道了mob-token该怎么获取，但是具体该怎么设置我还是不太懂，希望您能教教我😭

**Comment by ghost** [comment]
README.md中已做相应补充，你可以看一看。

**Comment by penperlpa** [comment]
好的好的，我明白了，谢谢您
